allowBuilds:
  esbuild: true
  msw: false
  sharp: true
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
overrides:
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
